### ISSUE TITLE
it.js contains unescaped single quotes

### ISSUE THREAD

**Issue by rob2universe** [bpmn-io/bpmn-js-i18n#12]
__Describe the Bug__
it.js contains unescaped single quotes in lines: 67, 77, 78

__Steps to Reproduce__

try to parse file or check it in IDE

__Expected Behavior__

valid file

__Environment__

N/A

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/bpmn-js-i18n/pull/13.
