### ISSUE TITLE
Provide `bpmn-js-i18n` as an npm package

### ISSUE THREAD

**Issue by corocoto** [bpmn-io/bpmn-js-i18n#20]
### Is your feature request related to a problem? Please describe.

I suppose that providing `bpmn-js-i18n` as an npm package can resolve the cases when UI can gloabally change (including text description), and you need to download it's new locale (translation) version. One thing that you should do - check  `bpmn-js-i18n` version and download it, if it necessary. Instead of going to the repo and copy content of related js file and paste it into your project.

It also useful for projects which have an oppotunity to switch between multiple locales. You shouldn't check each properly file and copy it from repo. You can also update npm package version, and take necessary files from it.

**Comment by nikku** [comment]
There you go. Released as v1.0.0.

**Comment by corocoto** [comment]
@nikku, thanks a lot
