### ISSUE TITLE
"Append TextAnnotation" title doesn't translate fully

### ISSUE THREAD

**Issue by corocoto** [bpmn-io/bpmn-js-i18n#22]
### Describe the Bug

I try to translate "Append TextAnnotation" to russian locale via additionalModules property: 

```js
additionalModules: [
  {
     translate: ['value', customTranslate(ruLocale)],
   },
],
```

The problem is that the word `TextAnnotation` doesn't translate, even if I put these properties into my locale file. It's that I mean:

```js
// ru.js
export default {
...
 'Append TextAnnotation': 'Добавить комментарий',
'Text Annotation': 'Комментарий',
'TextAnnotation': 'Комментарий',
}
```

### Steps to Reproduce

1. Use  `additionalModules` property with `translate` block:
```js
additionalModules: [
  {
     translate: ['value', customTranslate([LOCALE FILE])],
   },
],
```

2. Add translations for "Append TextAnnotation", "Text Annotation" and "TextAnnotation" text blocks into your locale file
3. Check result:

![image](https://github.com/bpmn-io/bpmn-js-i18n/assets/37180024/0e124683-90c8-495e-af3b-c0883611e406)

### Expected Behavior

"Append TextAnnotation" should translated fully, but not only "Append" word.

### Environment

- Host (Browser/Node version), if applicable: Chrome 114.0.5735.198 
- OS: macOS Ventura v.13.4.1
- Library version: Latest

**Comment by philippfromme** [comment]
Currently, element types are not translated (cf. https://github.com/bpmn-io/bpmn-js/blob/develop/lib/features/context-pad/ContextPadProvider.js#L238). You'd have to override the provider or the [translate service](https://github.com/bpmn-io/diagram-js/blob/develop/lib/i18n/translate/translate.js) to change this behavior.

**Comment by nikku** [comment]
@corocoto Happy to take a contribution to translate the element types.

**Comment by corocoto** [comment]
@nikku, yeah, sure

**Comment by corocoto** [comment]
@nikku, @philippfromme, done. You can review these PR's.
