### ISSUE TITLE
Use orthography checker on CI or as a pre-commit hook

### ISSUE THREAD

**Issue by corocoto** [bpmn-io/bpmn-js-i18n#24]
### Is your feature request related to a problem? Please describe.

This feature allows contributors detect word typos or orthography errors on earlier step. People, who will use or already using this package, reduce the percent to meet with these problems.

### Describe the solution you'd like

As example, we can use https://github.com/hcodes/yaspeller library to check and detect orthography errors. But the problem of this package is that it only support English, Russian and Ukrainian languages right now.

Anyway, we can do research and find an alternative packages that can cover more languages.

**Comment by nikku** [comment]
Let's not bloat the scope of this repository. I think it is fine to pipe the translations to a simple ortography checker (google docs) before submission.
